package org.xykine.payroll.model.enums;

public enum PaymentTypeEnum {
    ALLOWANCE_ANNUAL_TRANSPORT("ANNUAL TRANSPORT ALLOWANCE"),
    ALLOWANCE_MONTHLY_TRANSPORT("MONTHLY TRANSPORT ALLOWANCE"),
    ALLOWANCE_WEEKLY_TRANSPORT("WEEKLY TRANSPORT ALLOWANCE"),
    ALLOWANCE_BIWEEKLY_TRANSPORT("BIWEEKLY TRANSPORT ALLOWANCE"),
    ALLOWANCE_ANNUAL_HOUSING("ANNUAL HOUSING ALLOWANCE"),
    ALLOWANCE_MONTHLY_HOUSING("MONTHLY HOUSING ALLOWANCE"),
    ALLOWANCE_WEEKLY_HOUSING("WEEKLY HOUSING ALLOWANCE"),
    ALLOWANCE_BIWEEKLY_HOUSING("BIWEEKLY HOUSING ALLOWANCE"),
    ALLOWANCE_ANNUAL("ANNUAL ALLOWANCE"),
    ALLOWANCE_WEEKLY("WEEKLY ALLOWANCE"),
    ALLOWANCE_BIWEEKLY("BIWEEKLY ALLOWANCE"),
    ALLOWANCE_MONTHLY("MONTHLY ALLOWANCE"),
    DEDUCTION_ANNUAL("ANNUAL DEDUCTION"),
    DEDUCTION_MONTHLY("MONTHLY DEDUCTION"),
    DEDUCTION_WEEKLY("WEEKLY DEDUCTION"),
    BASIC_SALARY_ANNUAL("BASIC SALARY ANNUAL"),
    OFF_CYCLE_PAYMENT_AMOUNT("OFF CYCLE PAYMENT AMOUNT");


    private final String description;

    PaymentTypeEnum(String aDescription){
        description = aDescription;
    }

    public String getDescription() {
        return description;
    }
}
